### ISSUE TITLE
[Feat] Extend Logging Capabilities

### ISSUE THREAD

**Issue by 8ear** [DCSO/TIE-Splunk-TA#2]
# Why: Why you want the feature
Currently the tie2index.py python script have no debug, error,info output for an administrator to check if the script is working.

# What: What you want to happen
Extend the logging capabilites of the python script. So that an administrator know in which state is the python script currently and is the script working.
Example:
http://dev.splunk.com/view/logging/SP-CAAAFCN

# How: How it is implemented
- [ ] Add logging splunk extension to python script

**Comment by geertjanvdk** [comment]
This is part of issue #10 : we log to the `dcso_tie.log` file when running within the Splunk environment, otherwise to `sys.stderr`.
