### ISSUE TITLE
[Feat] IoC Filter for Severity and Confidence via Web UI

### ISSUE THREAD

**Issue by 8ear** [DCSO/TIE-Splunk-TA#6]
# Why

It is uncomfortable and not always possible that the Splunk user can change the severity and confidence via shell on the server itself.

# What

The min/max severity and confidence should be able to setup in the Web UI. This settings should only be available if the user activate additional settings.

# How

- [ ] ...

**Comment by geertjanvdk** [comment]
This is now supported in 2.0.0b1. Min/Max can be used as well as setting a particular value for severity and confidence.
